### ISSUE TITLE
Seeing lots of "Repository for endpoint ... not initialized" and "Error executing union operator: null"

### ISSUE THREAD

**Issue by tfrancart** [VeritasOS/fedx#5] opened 2019-01-29 15:15 UTC
I am currently testing FedX.
I try to query the following federation :

```
			List<Endpoint> endpoints = new ArrayList<Endpoint>();			
			endpoints.add( EndpointFactory.loadSPARQLEndpoint("arsol", "http://localhost:7200/repositories/openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr"));
			endpoints.add( EndpointFactory.loadSPARQLEndpoint("aerba", "http://localhost:7200/repositories/openarchaeo?default-graph-uri=http%3A%2F%2Faerba.univ-tours.fr"));
			endpoints.add( EndpointFactory.loadSPARQLEndpoint("referentiels", "http://localhost:7200/repositories/openarchaeo-referentiels"));
```

With Log4J debug activated, I see a lot of errors like this :

```
31930 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31930 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31930 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31931 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31931 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31931 [Join Scheduler-10] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
31867 [Join Scheduler-1] WARN com.fluidops.fedx.evaluation.concurrent.ControlledWorkerScheduler  - Exception encountered while evaluating task (QueryEvaluationException): com.fluidops.fedx.exception.FedXRuntimeException: Repository for endpoint sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr not initialized
```

And also a few like that :

```
47057 [Join Scheduler-8] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47099 [Join Scheduler-2] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47110 [Join Scheduler-4] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47118 [Join Scheduler-3] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47132 [Join Scheduler-6] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47212 [Join Scheduler-7] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47229 [Join Scheduler-9] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
47244 [Join Scheduler-5] WARN com.fluidops.fedx.evaluation.union.UnionExecutorBase  - Error executing union operator: null
```

And the query seems to hang and never returns.

Any idea what can cause these 2 errors ?
Interestingly, if I remove one of the endpoints in the federation, the query performs fine.
The triplestore is GraphDB.

How can I get more debug information on what is currently happing inside FedX ?

FWIW, here is the SPARQL query and its execution plan 

```
SELECT DISTINCT  ?this ?thisLabel
WHERE
  { ?this  a                     <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object> .
    ?this (<http://www.ics.forth.gr/isl/CRMsci/O19i_was_object_found_by>/<http://www.cidoc-crm.org/cidoc-crm/P8_took_place_on_or_within>)|<http://www.ics.forth.gr/isl/CRMarchaeo/AP21i_is_contained_in> ?Site1 .
    ?Site1  a                     <http://www.cidoc-crm.org/cidoc-crm/E27_Site> .
    ?Site1 <http://www.cidoc-crm.org/cidoc-crm/P8i_witnessed>/<http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by> <https://halshs.archives-ouvertes.fr/search/index/q/*/contributorId_i/103825/> .
    OPTIONAL
      { ?this  <http://www.w3.org/2004/02/skos/core#prefLabel>  ?thisLabel}
  }
7248 [main] DEBUG com.fluidops.fedx.FedXConnection  - Optimization start
7277 [main] DEBUG com.fluidops.fedx.optimizer.StatementGroupOptimizer  - Join arguments could be reduced to a single argument, replacing join node.
7277 [main] DEBUG com.fluidops.fedx.FedXConnection  - Optimization duration: 29
Optimized query execution plan: 
QueryRoot
   Distinct
      Projection
         ProjectionElemList
            ProjectionElem "this"
            ProjectionElem "thisLabel"
         LeftJoin
            NJoin
               ExclusiveGroup
                  ExclusiveStatement
                     Var (name=this)
                     Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                     Var (name=_const_e4a0c91_uri, value=http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object, anonymous)
                     StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
                  ExclusiveStatement
                     Var (name=_anon_d5e73e6a_4e89_4b72_bfa1_450d50e722b8, anonymous)
                     Var (name=_const_35bfec94_uri, value=http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by, anonymous)
                     Var (name=_const_775f2f14_uri, value=https://halshs.archives-ouvertes.fr/search/index/q/*/contributorId_i/103825/, anonymous)
                     StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
               StatementSourcePattern
                  Var (name=Site1)
                  Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                  Var (name=_const_9d328667_uri, value=http://www.cidoc-crm.org/cidoc-crm/E27_Site, anonymous)
                  StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Faerba.univ-tours.fr, type=REMOTE)
                  StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
               StatementSourcePattern
                  Var (name=Site1)
                  Var (name=_const_9c6af60f_uri, value=http://www.cidoc-crm.org/cidoc-crm/P8i_witnessed, anonymous)
                  Var (name=_anon_d5e73e6a_4e89_4b72_bfa1_450d50e722b8, anonymous)
                  StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Faerba.univ-tours.fr, type=REMOTE)
                  StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
               NUnion
                  ExclusiveGroup
                     ExclusiveStatement
                        Var (name=this)
                        Var (name=_const_440507c3_uri, value=http://www.ics.forth.gr/isl/CRMsci/O19i_was_object_found_by, anonymous)
                        Var (name=_anon_db9424a9_ce5b_4399_9647_687bf8269037, anonymous)
                        StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
                     ExclusiveStatement
                        Var (name=_anon_db9424a9_ce5b_4399_9647_687bf8269037, anonymous)
                        Var (name=_const_e772e6db_uri, value=http://www.cidoc-crm.org/cidoc-crm/P8_took_place_on_or_within, anonymous)
                        Var (name=Site1)
                        StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
                  ExclusiveStatement
                     Var (name=this)
                     Var (name=_const_2dea2a6c_uri, value=http://www.ics.forth.gr/isl/CRMarchaeo/AP21i_is_contained_in, anonymous)
                     Var (name=Site1)
                     StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
            ExclusiveStatement
               Var (name=this)
               Var (name=_const_c9f3cb8c_uri, value=http://www.w3.org/2004/02/skos/core#prefLabel, anonymous)
               Var (name=thisLabel)
               StatementSource (id=sparql_localhost:7200_repositories_openarchaeo?default-graph-uri=http%3A%2F%2Farsol.univ-tours.fr, type=REMOTE)
```

**Comment by aschwarte10** [comment] 2019-02-01 06:37
Hmm, this looks strange. From the error message it appears that one of the Repository instances (i.e. the holding object for the connection to the federation member) is not initialized at the time of evaluation.

It also looks that it is always the same one of the arsol dataset. Is there something special about this particular endpoint?

Can you share a bit of code of how you initialize FedX and how you invoke your query? It looks like the initialization of the endpoint fails at some point, but is unclear when and why. It looks like the initial connection is working though, as the optimizer yields results.

**Comment by aschwarte10** [comment] 2019-02-18 07:56
It is unclear to me currently in which case the underlying connections get closed, such that you get to the observed state.
When I find some spare time I will try to dig into this further and try to understand the cause.

**Comment by aschwarte10** [comment] 2019-03-08 14:48
@tfrancart just a quick heads up: I am currently preparing test infrastructure to simulate errorneous server communications. With these tests I identified some smaller issues already (similar to what you have seen), but I have not been able to reproduce your observation yet. WIll continue to look into this and keep you posted

**Comment by aschwarte10** [comment] 2019-03-12 11:58
@tfrancart I have added quite a number of changes to make the error handling (especially in case of concurrent subquery evaluation) more consistent. Hopefully this also improves above situation, and at least gives a more precise cause for the error.

Could you by chance try a new snapshot build from latest master in your environment and let me know about your observations?

**Comment by aschwarte10** [comment] 2019-04-08 14:19
Quite a number of improvements have been added to the FedX code base which should also improve above behavior.

I suggest closing this issue as I do not see concrete tasks any more.

@tfrancart please feel free to re-open or file new issues if your concrete problem still exists

**Closed by aschwarte10** 2019-04-08 14:19 UTC
